export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_REGISTER_REQUEST = 'PRODUCT_REGISTER_REQUEST';
export const PRODUCT_REGISTER_SUCCESS = 'PRODUCT_REGISTER_SUCCESS';
export const PRODUCT_REGISTER_FAIL = 'PRODUCT_REGISTER_FAIL';

export const PRODUCT_RATINGS_REQUEST = 'PRODUCT_RATINGS_REQUEST';
export const PRODUCT_RATINGS_SUCCESS = 'PRODUCT_RATINGS_SUCCESS';
export const PRODUCT_RATINGS_FAIL = 'PRODUCT_RATINGS_FAIL';