export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_REGISTER_REQUEST = 'PRODUCT_REGISTER_REQUEST';
export const PRODUCT_REGISTER_SUCCESS = 'PRODUCT_REGISTER_SUCCESS';
export const PRODUCT_REGISTER_FAIL = 'PRODUCT_REGISTER_FAIL';

export const PRODUCT_BY_CATEGORT_REQUEST = 'PRODUCT_BY_CATEGORT_REQUEST';
export const PRODUCT_BY_CATEGORT_RSUCCESS = 'PRODUCT_BY_CATEGORT_RSUCCESS';
export const PRODUCT_BY_CATEGORT_FAIL = 'PRODUCT_BY_CATEGORT_FAIL';